FROM python:3.8

WORKDIR /usr/src/app

COPY Twitter_chat/requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir git+git://github.com/gunthercox/chatterbot-corpus.git
RUN python -m spacy download en
RUN python -m spacy download pt
COPY Twitter_chat/ .
COPY corpora ./corpora


CMD [ "python", "./twchat.py" ]