FROM python:3.8

WORKDIR /usr/src/app

COPY Twitter_chat/requirements.txt ./
COPY corpora/ ./
RUN pip install --no-cache-dir -r requirements.txt
RUN python -m spacy download en
RUN python -m spacy download pt

COPY Twitter_chat/ .

CMD [ "python", "./twchat.py" ]