HOST_UID=$HOST_UID
HOST_GID=$HOST_GID

BOT_TOKEN=$BOT_TOKEN

# Database
PSQL_DB=$PSQL_DB
PSQL_USER=$PSQL_USER
PSQL_PASSWORD=$PSQL_PASSWORD
PSQL_HOST=$PSQL_HOST
PSQL_PORT=$PSQL_PORT
PSQL_BOTDB=$PSQL_BOTDB
VIGIBOT_PG_DATA=$VIGIBOT_PG_DATA

# Twitter_chat
TWITTER_API_KEY=$TWITTER_API_KEY
TWITTER_API_SECRET_KEY=$TWITTER_API_SECRET_KEY
TWITTER_ACCESS_TOKEN=$TWITTER_ACCESS_TOKEN
TWITTER_ACCESS_TOKEN_SECRET=$TWITTER_ACCESS_TOKEN_SECRET
