version: '3'
services:
  bot:
    build:
      context: ".."
      dockerfile: containers/Dockerfile-tw
    env_file:
      - ../.env
    hostname: bot
    container_name: bot
    environment:
      - PSQL_HOST=${PSQL_HOST}
      - PSQL_PORT=${PSQL_PORT}
    # CMD [ "python", "./vbot.py" ]
    command: ["python", "./vbot.py"]
    restart: always


  twitterchat:
    build:
      context: ".."
      dockerfile: containers/Dockerfile-tw
    env_file:
      - ../.env
    hostname: twitterchat
    container_name: twitterchat
    environment:
      - PSQL_HOST=${PSQL_HOST}
      - PSQL_PORT=${PSQL_PORT}
    # CMD [ "python", "./twbot.py" ]
    command: ["python", "./twbot.py"]
    depends_on:
      - bot
    restart: always
