# ref: https://github.com/mamba-org/micromamba-docker/blob/main/Dockerfile

FROM condaforge/mambaforge:latest

LABEL maintainer="Flávio Codeço Coelho <fccoelho@gmail.com>"
LABEL org.opencontainers.image.title="VigiBot"
LABEL org.opencontainers.image.authors="VigiBot Team"
LABEL org.opencontainers.image.source="https://github.com/AlertaDengue/vigibot.git"
LABEL org.opencontainers.image.version="latest"
LABEL org.opencontainers.image.description="telegram and twitter bots"
LABEL org.thegraphnetwork.vigibot.version="latest"

# it is the default, but using it here to have it explicitly
USER root

SHELL ["/bin/bash", "-c"]
# Use bash in Dockerfile RUN commands and make sure bashrc is sourced when
# executing commands with /bin/bash -c
# Needed to have the micromamba activate command configured etc.

ENV ENV_NAME=chatterbot
ENV DEBIAN_FRONTEND=noninteractive
ARG UID=1000
ARG GID=1000

RUN apt-get update -y \
  && apt-get install -y \
    build-essential \
    curl \
    tini \
  && rm -rf /var/lib/apt/lists/* \
    /var/cache/apt/archives \
    /tmp/*

RUN addgroup --gid ${GID} vigibot \
  && useradd --uid ${UID} --gid ${GID} -ms /bin/bash vigibot \
  && mkdir -p /opt/services \
  && chmod -R a+rwx /opt/conda /opt/services \
  && export ENV_NAME="$ENV_NAME" \
  && chown vigibot:vigibot /opt/services

USER vigibot

COPY --chown=vigibot:vigibot ./conda/ /tmp/conda
COPY --chown=vigibot:vigibot app /opt/services/app/
COPY --chown=vigibot:vigibot poetry.lock pyproject.toml README.md LICENSE /opt/

ENV PATH /opt/conda/envs/$ENV_NAME/bin:$PATH
ENV PYTHONPATH='/opt/services/app'

RUN mamba env create -n $ENV_NAME --file /tmp/conda/containers.yaml \
  && conda clean --all \
  && find /opt/conda/ -type f,l -name '*.a' -delete \
  && find /opt/conda/ -type f,l -name '*.pyc' -delete \
  && find /opt/conda/ -type f,l -name '*.js.map' -delete \
  && rm -rf /opt/conda/pkgs /tmp/*

WORKDIR /opt/

RUN poetry config virtualenvs.create false \
  && poetry install

RUN python -m spacy download en
RUN python -m spacy download pt

COPY --chown=vigibot:vigibot containers/entrypoint.sh /opt/entrypoint.sh

RUN chmod +x /opt/entrypoint.sh \
  && echo "source /opt/entrypoint.sh" > ~/.bashrc

ENTRYPOINT ["tini", "--", "/opt/entrypoint.sh"]

WORKDIR /opt/services/app/
