version: '3'
services:
  base:
    build:
      context: ".."
      dockerfile: "docker/Dockerfile-base"
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    restart: always

  bot:
    build:
      context: ".."
      dockerfile: "docker/Dockerfile-bot"
      args:
        IMAGE_BUILD: vigibot_base:latest
    env_file:
      - ../.env
    hostname: bot
    container_name: bot
    restart: always

  twitterchat:
    build:
      context: ".."
      dockerfile: "docker/Dockerfile-tw"
      args:
        IMAGE_BUILD: vigibot_base:latest
    env_file:
      - ../.env
    hostname: twitterchat
    container_name: twitterchat
    restart: always
