name: vigibot-docker

on: [push, pull_request]

env:
  HOST_UID: 1000
  HOST_GID: 1000
  TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
  TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
  TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
  TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  PSQL_USER: ${{ secrets.PSQL_USER }}
  PSQL_PASSWORD: ${{ secrets.PSQL_PASSWORD }}
  PSQL_HOST: ${{ secrets.PSQL_HOST }}
  PSQL_PORT: ${{ secrets.PSQL_PORT }}
  PSQL_DB: ${{ secrets.PSQL_DB }}
  PSQL_BOTDB: ${{ secrets.PSQL_BOTDB }}
  VIGIBOT_PG_DATA: ${{ secrets.VIGIBOT_PG_DATA }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        mamba-version: "*"
        environment-file: conda/environment.yaml
        channels: conda-forge,nodefaults
        activate-environment: chatterbot
        use-mamba: true
        miniforge-variant: Mambaforge

    - name: Create env file
      run: envsubst < env.tpl > .env

    - name: Docker build all images
      run: |
        make docker-build

    - name: Docker pytest
      run: |
        make docker-start SERVICES=db
        make docker-pytest-ci SERVICES=twitterchat
